name: build frontend
on:
  push:
    tags:
      - "*"
    branches:
      - 'master'

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: build FE
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install -g yarn
          yarn
          yarn build
          zip -r build.zip build/
          ls

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: build.zip
